export const KEYS = {
  userToken: 'jwt',
};

export enum ContentType {
}

export const MARKS_LIST = [
  { label: 'Audi', value: 'audi' },
  { label: 'BMW', value: 'bmw' },
  { label: 'Mercedes-Benz', value: 'mercedes-benz' },
  { label: 'Toyota', value: 'toyota' },
  { label: 'Ford', value: 'ford' },
  { label: 'Honda', value: 'honda' },
  { label: 'Chevrolet', value: 'chevrolet' },
  { label: 'Volkswagen', value: 'volkswagen' },
  { label: 'Nissan', value: 'nissan' },
  { label: 'Hyundai', value: 'hyundai' },
  { label: 'Kia', value: 'kia' },
  { label: 'Subaru', value: 'subaru' },
  { label: 'Mazda', value: 'mazda' },
  { label: 'Lexus', value: 'lexus' },
  { label: 'Jeep', value: 'jeep' },
  { label: 'Porsche', value: 'porsche' },
  { label: 'Volvo', value: 'volvo' },
  { label: 'Jaguar', value: 'jaguar' },
  { label: 'Land Rover', value: 'land-rover' },
  { label: 'Ferrari', value: 'ferrari' },
  { label: 'Lamborghini', value: 'lamborghini' },
  { label: 'Maserati', value: 'maserati' },
  { label: 'Bentley', value: 'bentley' },
  { label: 'Rolls-Royce', value: 'rolls-royce' },
  { label: 'Aston Martin', value: 'aston-martin' },
  { label: 'Alfa Romeo', value: 'alfa-romeo' },
  { label: 'Cadillac', value: 'cadillac' },
  { label: 'Chrysler', value: 'chrysler' },
  { label: 'Dodge', value: 'dodge' },
  { label: 'Ram', value: 'ram' },
  { label: 'GMC', value: 'gmc' },
  { label: 'Buick', value: 'buick' },
  { label: 'Acura', value: 'acura' },
  { label: 'Infiniti', value: 'infiniti' },
  { label: 'Tesla', value: 'tesla' },
  { label: 'Mitsubishi', value: 'mitsubishi' },
  { label: 'Suzuki', value: 'suzuki' },
  { label: 'Mini', value: 'mini' },
  { label: 'Fiat', value: 'fiat' },
  { label: 'Peugeot', value: 'peugeot' },
  { label: 'Citroën', value: 'citroen' },
  { label: 'Renault', value: 'renault' },
  { label: 'Seat', value: 'seat' },
  { label: 'Skoda', value: 'skoda' },
  { label: 'Opel', value: 'opel' },
  { label: 'Vauxhall', value: 'vauxhall' },
  { label: 'Saab', value: 'saab' },
  { label: 'Lancia', value: 'lancia' },
  { label: 'Pagani', value: 'pagani' },
  { label: 'Koenigsegg', value: 'koenigsegg' },
  { label: 'Bugatti', value: 'bugatti' },
  { label: 'McLaren', value: 'mclaren' },
  { label: 'Rivian', value: 'rivian' },
  { label: 'Lucid', value: 'lucid' },
  { label: 'Genesis', value: 'genesis' },
  { label: 'Dacia', value: 'dacia' },
  { label: 'Holden', value: 'holden' },
  { label: 'Geely', value: 'geely' },
  { label: 'Great Wall', value: 'great-wall' },
  { label: 'Tata', value: 'tata' },
  { label: 'Mahindra', value: 'mahindra' },
  { label: 'Maruti Suzuki', value: 'maruti-suzuki' },
  { label: 'BYD', value: 'byd' },
  { label: 'Changan', value: 'changan' },
  { label: 'Chery', value: 'chery' },
  { label: 'Haval', value: 'haval' },
  { label: 'Lifan', value: 'lifan' },
  { label: 'MG', value: 'mg' },
  { label: 'Roewe', value: 'roewe' },
  { label: 'Zotye', value: 'zotye' },
  { label: 'Proton', value: 'proton' },
  { label: 'Perodua', value: 'perodua' },
  { label: 'Isuzu', value: 'isuzu' },
  { label: 'Foton', value: 'foton' },
  { label: 'Baojun', value: 'baojun' },
  { label: 'Hongqi', value: 'hongqi' },
  { label: 'Wuling', value: 'wuling' },
  { label: 'Dongfeng', value: 'dongfeng' },
  { label: 'FAW', value: 'faw' },
  { label: 'Brilliance', value: 'brilliance' },
  { label: 'JAC', value: 'jac' },
  { label: 'Nio', value: 'nio' },
  { label: 'XPeng', value: 'xpeng' },
  { label: 'VinFast', value: 'vinfast' },
  { label: 'Smart', value: 'smart' },
  { label: 'Saic', value: 'saic' },
  { label: 'Togg', value: 'togg' },
  { label: 'Ora', value: 'ora' },
  { label: 'Polestar', value: 'polestar' },
  { label: 'Ariel', value: 'ariel' },
  { label: 'Caterham', value: 'caterham' },
  { label: 'Ginetta', value: 'ginetta' },
  { label: 'TVR', value: 'tvr' },
  { label: 'SSC', value: 'ssc' },
  { label: 'De Tomaso', value: 'de-tomaso' },
  { label: 'Hennessey', value: 'hennessey' },
  { label: 'Saleen', value: 'saleen' },
  { label: 'Spyker', value: 'spyker' }
];

